---
# module: ara_install/tasks/configure_server
# description: Configure ara_install for the ara server

- name: Create folder path with apache permissions
  file: path="{{ ara_server_path }}" state=directory owner=www-data group=www-data

- name: Create apache config for the ARA site
  template: src=ara_apache.conf.j2 dest=/etc/apache2/sites-available/ara_apache.conf owner=www-data group=www-data
  notify: restart apache2 service

- name: Create a wsgi template
  template: src=ara.wsgi.j2 dest="{{ ara_server_path }}/ara.wsgi" owner=www-data group=www-data
  notify: restart apache2 service

- name: Create ansible ARA configuration
  template: src=ansible.cfg.j2 dest="{{ ara_server_path }}/ansible.cfg" owner=www-data group=www-data
  notify: restart apache2 service

- name: Enable Apache module
  file: src=/etc/apache2/sites-available/ara_apache.conf dest=/etc/apache2/sites-enabled/ara_apache.conf state=link
  notify: restart apache2 service

- name: Disable default Apache module
  file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2 service
