---
# module: ara_install/tasks/configure_client
# description: Configure ara_install for the client

- name: Create environment variables script allowing Ansible to send data back to ARA
  template: src=ara_env_vars.sh.j2 dest="/etc/profile.d/ara_env_vars.sh.j2" owner=root group=root mode=0644
