---
# module: ara_install/tasks/install
# description: Install our required packages for ara_install

- name: Install all required packages for ara_install
  apt: pkg={{ packages }} state=latest

- name: Install all required packages for ara_install server
  apt: pkg={{ ara_server_packages }} state=latest
  when: ara_install_type == "server"

- name: Install password module when apache auth is enabled and server mode is on.
  apt: pkg=python-passlib state=latest
  when: 
    - ara_apache_auth_enabled == true
    - ara_install_type == "server"

- name: Enable and start Apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: ara_install_type == "server"

- name: Update PIP to latest version using PIP
  pip:
    name: pip
    state: latest

- name: Install ara package using PIP - specified version
  pip:
    name: ara
    version: "{{ ara_version }}"
  when: ara_version

- name: Install ara package using PIP - latest version
  pip:
    name: ara
    state: latest
  when: ara_version == ""
